### ISSUE TITLE
add custom properties to Language

### ISSUE THREAD

**Issue by vadekh** [digitallinguistics/javascript#131]
change the init process to something resembling this code: 

`Object.assign(this, data);
this.name = data.name;`
This will allow custom properties to be initialized, such as a deleted flag property to use in the app repo.

**Comment by dwhieb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[javascript]: allow custom properties on Language](https://trello.com/c/gZuzFPYr/21-javascript-allow-custom-properties-on-language)
